# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 595)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget0 = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget0.setObjectName("tabWidget0")
        self.tabWidget0_Page1 = QtWidgets.QWidget()
        self.tabWidget0_Page1.setObjectName("tabWidget0_Page1")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tabWidget0_Page1)
        self.gridLayout_9.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pcv_img = ImageView(self.tabWidget0_Page1)
        self.pcv_img.setObjectName("pcv_img")
        self.gridLayout.addWidget(self.pcv_img, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tabWidget0_Page1)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.sld_slice = QtWidgets.QSlider(self.groupBox)
        self.sld_slice.setOrientation(QtCore.Qt.Horizontal)
        self.sld_slice.setObjectName("sld_slice")
        self.gridLayout_8.addWidget(self.sld_slice, 0, 1, 1, 1)
        self.spb_slice = QtWidgets.QSpinBox(self.groupBox)
        self.spb_slice.setObjectName("spb_slice")
        self.gridLayout_8.addWidget(self.spb_slice, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 1, 1)
        self.sld_echo = QtWidgets.QSlider(self.groupBox)
        self.sld_echo.setOrientation(QtCore.Qt.Horizontal)
        self.sld_echo.setObjectName("sld_echo")
        self.gridLayout_8.addWidget(self.sld_echo, 1, 1, 1, 1)
        self.spb_echo = QtWidgets.QSpinBox(self.groupBox)
        self.spb_echo.setObjectName("spb_echo")
        self.gridLayout_8.addWidget(self.spb_echo, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget0.addTab(self.tabWidget0_Page1, "")
        self.gridLayout_4.addWidget(self.tabWidget0, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.information_tab = QtWidgets.QWidget()
        self.information_tab.setObjectName("information_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.information_tab)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radio_summary_header = QtWidgets.QRadioButton(self.information_tab)
        self.radio_summary_header.setChecked(True)
        self.radio_summary_header.setObjectName("radio_summary_header")
        self.gridLayout_5.addWidget(self.radio_summary_header, 0, 0, 1, 1)
        self.radio_full_header = QtWidgets.QRadioButton(self.information_tab)
        self.radio_full_header.setObjectName("radio_full_header")
        self.gridLayout_5.addWidget(self.radio_full_header, 0, 1, 1, 1)
        self.textedit_header = QtWidgets.QTextEdit(self.information_tab)
        self.textedit_header.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textedit_header.setObjectName("textedit_header")
        self.gridLayout_5.addWidget(self.textedit_header, 1, 0, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.information_tab, "")
        self.fatmap_tab = QtWidgets.QWidget()
        self.fatmap_tab.setObjectName("fatmap_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.fatmap_tab)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pcv_fatmap = ImageView(self.fatmap_tab)
        self.pcv_fatmap.setMouseTracking(True)
        self.pcv_fatmap.setObjectName("pcv_fatmap")
        self.gridLayout_2.addWidget(self.pcv_fatmap, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.fatmap_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.cbx_methods = QtWidgets.QComboBox(self.groupBox_2)
        self.cbx_methods.setObjectName("cbx_methods")
        self.gridLayout_3.addWidget(self.cbx_methods, 0, 1, 1, 1)
        self.check_current_slice = QtWidgets.QCheckBox(self.groupBox_2)
        self.check_current_slice.setToolTip("")
        self.check_current_slice.setToolTipDuration(-1)
        self.check_current_slice.setWhatsThis("")
        self.check_current_slice.setObjectName("check_current_slice")
        self.gridLayout_3.addWidget(self.check_current_slice, 1, 0, 1, 1)
        self.btn_cfatmap = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cfatmap.sizePolicy().hasHeightForWidth())
        self.btn_cfatmap.setSizePolicy(sizePolicy)
        self.btn_cfatmap.setObjectName("btn_cfatmap")
        self.gridLayout_3.addWidget(self.btn_cfatmap, 1, 1, 1, 1)
        self.check_current_slice.raise_()
        self.label_4.raise_()
        self.cbx_methods.raise_()
        self.btn_cfatmap.raise_()
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.fatmap_tab, "")
        self.signal_tab = QtWidgets.QWidget()
        self.signal_tab.setObjectName("signal_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.signal_tab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.btn_roi_delete = QtWidgets.QPushButton(self.signal_tab)
        self.btn_roi_delete.setObjectName("btn_roi_delete")
        self.gridLayout_10.addWidget(self.btn_roi_delete, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.signal_tab)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 3, 0, 1, 2)
        self.cbox_rois = QtWidgets.QComboBox(self.signal_tab)
        self.cbox_rois.setObjectName("cbox_rois")
        self.gridLayout_10.addWidget(self.cbox_rois, 0, 0, 1, 1)
        self.pcv_signal = PlotWidget(self.signal_tab)
        self.pcv_signal.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pcv_signal.sizePolicy().hasHeightForWidth())
        self.pcv_signal.setSizePolicy(sizePolicy)
        self.pcv_signal.setObjectName("pcv_signal")
        self.gridLayout_10.addWidget(self.pcv_signal, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.signal_tab)
        self.label.setObjectName("label")
        self.gridLayout_10.addWidget(self.label, 1, 0, 1, 3)
        self.textEdit_roi = QtWidgets.QTextEdit(self.signal_tab)
        self.textEdit_roi.setObjectName("textEdit_roi")
        self.gridLayout_10.addWidget(self.textEdit_roi, 4, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout_10)
        self.tabWidget.addTab(self.signal_tab, "")
        self.export_tab = QtWidgets.QWidget()
        self.export_tab.setObjectName("export_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.export_tab)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_12.setSpacing(6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBox_4 = QtWidgets.QGroupBox(self.export_tab)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.check_anonimyze = QtWidgets.QCheckBox(self.groupBox_4)
        self.check_anonimyze.setEnabled(False)
        self.check_anonimyze.setObjectName("check_anonimyze")
        self.verticalLayout_4.addWidget(self.check_anonimyze)
        self.gridLayout_12.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.export_tab)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.radio_export_dicom = QtWidgets.QRadioButton(self.groupBox_5)
        self.radio_export_dicom.setObjectName("radio_export_dicom")
        self.gridLayout_11.addWidget(self.radio_export_dicom, 0, 0, 1, 1)
        self.radio_export_bitmap = QtWidgets.QRadioButton(self.groupBox_5)
        self.radio_export_bitmap.setObjectName("radio_export_bitmap")
        self.gridLayout_11.addWidget(self.radio_export_bitmap, 0, 1, 1, 1)
        self.check_export_dicom = QtWidgets.QCheckBox(self.groupBox_5)
        self.check_export_dicom.setTristate(True)
        self.check_export_dicom.setObjectName("check_export_dicom")
        self.gridLayout_11.addWidget(self.check_export_dicom, 1, 0, 1, 1)
        self.check_export_triple = QtWidgets.QCheckBox(self.groupBox_5)
        self.check_export_triple.setTristate(True)
        self.check_export_triple.setObjectName("check_export_triple")
        self.gridLayout_11.addWidget(self.check_export_triple, 2, 0, 1, 1)
        self.check_export_multi = QtWidgets.QCheckBox(self.groupBox_5)
        self.check_export_multi.setTristate(True)
        self.check_export_multi.setObjectName("check_export_multi")
        self.gridLayout_11.addWidget(self.check_export_multi, 3, 0, 1, 1)
        self.check_export_ann = QtWidgets.QCheckBox(self.groupBox_5)
        self.check_export_ann.setTristate(True)
        self.check_export_ann.setObjectName("check_export_ann")
        self.gridLayout_11.addWidget(self.check_export_ann, 4, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.export_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_13.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_13.setSpacing(6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.check_export_csv = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_export_csv.setChecked(True)
        self.check_export_csv.setObjectName("check_export_csv")
        self.gridLayout_13.addWidget(self.check_export_csv, 0, 0, 1, 1)
        self.check_include_csv_hdr = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_include_csv_hdr.setObjectName("check_include_csv_hdr")
        self.gridLayout_13.addWidget(self.check_include_csv_hdr, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.btn_export = QtWidgets.QPushButton(self.export_tab)
        self.btn_export.setObjectName("btn_export")
        self.gridLayout_12.addWidget(self.btn_export, 3, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_12)
        self.tabWidget.addTab(self.export_tab, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 865, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuLivertool = QtWidgets.QMenu(self.menuBar)
        self.menuLivertool.setObjectName("menuLivertool")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.act_open_single = QtWidgets.QAction(MainWindow)
        self.act_open_single.setObjectName("act_open_single")
        self.act_rectangle = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-Rectangular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_rectangle.setIcon(icon)
        self.act_rectangle.setObjectName("act_rectangle")
        self.act_ellipse = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icons8-Oval Filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_ellipse.setIcon(icon1)
        self.act_ellipse.setObjectName("act_ellipse")
        self.act_polygon = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icons8-Polygon Filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_polygon.setIcon(icon2)
        self.act_polygon.setObjectName("act_polygon")
        self.act_ROI_done = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/icons8-Ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_ROI_done.setIcon(icon3)
        self.act_ROI_done.setObjectName("act_ROI_done")
        self.act_ROI_cancel = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/icons8-Cancel_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.act_ROI_cancel.setIcon(icon4)
        self.act_ROI_cancel.setObjectName("act_ROI_cancel")
        self.act_open_multiple = QtWidgets.QAction(MainWindow)
        self.act_open_multiple.setObjectName("act_open_multiple")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.act_open_parrec = QtWidgets.QAction(MainWindow)
        self.act_open_parrec.setObjectName("act_open_parrec")
        self.menuLivertool.addAction(self.act_open_single)
        self.menuLivertool.addAction(self.act_open_multiple)
        self.menuLivertool.addSeparator()
        self.menuLivertool.addAction(self.act_open_parrec)
        self.menuBar.addAction(self.menuLivertool.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.toolBar.addAction(self.act_rectangle)
        self.toolBar.addAction(self.act_ellipse)
        self.toolBar.addAction(self.act_polygon)
        self.toolBar.addAction(self.act_ROI_done)
        self.toolBar.addAction(self.act_ROI_cancel)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.sld_slice.valueChanged['int'].connect(self.spb_slice.setValue)
        self.spb_slice.valueChanged['int'].connect(self.sld_slice.setValue)
        self.sld_echo.valueChanged['int'].connect(self.spb_echo.setValue)
        self.spb_echo.valueChanged['int'].connect(self.sld_echo.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Livertool"))
        self.groupBox.setTitle(_translate("MainWindow", "Navigation"))
        self.label_2.setText(_translate("MainWindow", "Slice"))
        self.label_3.setText(_translate("MainWindow", "Echo"))
        self.tabWidget0.setTabText(self.tabWidget0.indexOf(self.tabWidget0_Page1), _translate("MainWindow", "File name"))
        self.radio_summary_header.setText(_translate("MainWindow", "Summary"))
        self.radio_full_header.setText(_translate("MainWindow", "View header file"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.information_tab), _translate("MainWindow", "Information"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings"))
        self.label_4.setText(_translate("MainWindow", "Fat Fraction estimation method:"))
        self.check_current_slice.setText(_translate("MainWindow", "Map only current slice"))
        self.btn_cfatmap.setText(_translate("MainWindow", "Start"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fatmap_tab), _translate("MainWindow", "Fat map"))
        self.btn_roi_delete.setText(_translate("MainWindow", "Delete"))
        self.label_6.setText(_translate("MainWindow", "Data and Fat fraction estimation"))
        self.label.setText(_translate("MainWindow", "Signal Intensity (a.u.) vs Echo time (ms)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.signal_tab), _translate("MainWindow", "ROI"))
        self.groupBox_4.setTitle(_translate("MainWindow", "General"))
        self.check_anonimyze.setToolTip(_translate("MainWindow", "<html><head/><body><p>Removes the name of the patient of the header and summary files.</p></body></html>"))
        self.check_anonimyze.setText(_translate("MainWindow", "Anonimyze data"))
        self.groupBox_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exports separate DICOM files for each dataset and estimation method, or separate bitmap images for each mapped slice in each method.</p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Fat fraction maps"))
        self.radio_export_dicom.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exporting in DICOM is available only for results performed over the whole dataset. The file will inherit the original header with few modifications.</p></body></html>"))
        self.radio_export_dicom.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.radio_export_dicom.setText(_translate("MainWindow", "DICOM"))
        self.radio_export_bitmap.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exporting in bitmap is available for when only selected slices of the dataset were mapped using one of the algorithms.</p></body></html>"))
        self.radio_export_bitmap.setText(_translate("MainWindow", "Bitmap"))
        self.check_export_dicom.setText(_translate("MainWindow", "Dixon"))
        self.check_export_triple.setText(_translate("MainWindow", "Triple"))
        self.check_export_multi.setText(_translate("MainWindow", "Multi"))
        self.check_export_ann.setText(_translate("MainWindow", "ANN"))
        self.groupBox_3.setTitle(_translate("MainWindow", "ROI information"))
        self.check_export_csv.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exports a csv (comma separated values) file containing information computed about the selected regions of interest, if any. Includes summary information about the test.</p></body></html>"))
        self.check_export_csv.setText(_translate("MainWindow", "Export .CSV"))
        self.check_include_csv_hdr.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exports a csv (comma separated values) file containing information computed about the selected regions of interest, if any. Includes summary information about the test.</p></body></html>"))
        self.check_include_csv_hdr.setText(_translate("MainWindow", "Include columns header"))
        self.btn_export.setText(_translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.export_tab), _translate("MainWindow", "Export results"))
        self.menuLivertool.setTitle(_translate("MainWindow", "File..."))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.act_open_single.setText(_translate("MainWindow", "Open a single DICOM file..."))
        self.act_rectangle.setText(_translate("MainWindow", "Rectangle"))
        self.act_ellipse.setText(_translate("MainWindow", "Ellipse"))
        self.act_polygon.setText(_translate("MainWindow", "Polygon"))
        self.act_ROI_done.setText(_translate("MainWindow", "Done"))
        self.act_ROI_cancel.setText(_translate("MainWindow", "Cancel"))
        self.act_open_multiple.setText(_translate("MainWindow", "Open multiple DICOM files..."))
        self.actionExport.setText(_translate("MainWindow", "Export results..."))
        self.act_open_parrec.setText(_translate("MainWindow", "Open PAR /REC files..."))

from pyqtgraph import ImageView, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

